# Generated by Django 5.0 on 2023-12-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_usersource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersource",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="database.user"
            ),
        ),
    ]
