# Generated by Django 5.0 on 2024-01-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0003_alter_usersource_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTrends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("lien", models.URLField()),
                ("date", models.CharField(max_length=255)),
                ("main_topics", models.CharField(max_length=255)),
                ("topics_secondaires", models.CharField(max_length=255)),
                ("mots_cles", models.TextField()),
                ("resume", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.user"
                    ),
                ),
            ],
        ),
    ]
