# Generated by Django 5.0 on 2024-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0004_usertrends"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("base_content", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True)),
                ("tone_of_voice", models.CharField(max_length=50)),
                ("content_goal", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=50)),
            ],
        ),
    ]
