# Generated by Django 5.0 on 2024-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
