# Generated by Django 5.0 on 2024-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0007_article_content_size_article_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
