# Generated by Django 5.0 on 2024-01-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0009_remove_user_company_remove_user_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="language",
            new_name="product",
        ),
        migrations.AddField(
            model_name="article",
            name="Company_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
