# Generated by Django 5.0 on 2024-01-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0010_rename_language_article_product_article_company_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="product",
            field=models.TextField(blank=True, null=True),
        ),
    ]
