# Generated by Django 5.0 on 2024-02-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0013_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("resume", models.TextField(verbose_name="Résumé")),
                ("main_topics", models.TextField(verbose_name="Sujets Principaux")),
                (
                    "secondary_topics",
                    models.TextField(verbose_name="Sujets Secondaires"),
                ),
                (
                    "ponderation",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Pondération"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
    ]
