# Generated by Django 5.0 on 2024-02-27 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0014_trend"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postUrl",
                    models.URLField(max_length=1024, verbose_name="URL du post"),
                ),
                ("postContent", models.TextField(verbose_name="Contenu du post")),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "profileUrl",
                    models.URLField(max_length=1024, verbose_name="URL du profil"),
                ),
                (
                    "postDate",
                    models.CharField(max_length=100, verbose_name="Date du post"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur lié",
                    ),
                ),
            ],
        ),
    ]
