# Generated by Django 5.0 on 2024-02-27 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0015_linkedinpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkedinpost",
            name="action",
        ),
        migrations.RemoveField(
            model_name="linkedinpost",
            name="user",
        ),
    ]
